/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoadTournamentImport } from './routes/loadTournament'
import { Route as CreateTournamentImport } from './routes/createTournament'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoadTournamentRoute = LoadTournamentImport.update({
  path: '/loadTournament',
  getParentRoute: () => rootRoute,
} as any)

const CreateTournamentRoute = CreateTournamentImport.update({
  path: '/createTournament',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/createTournament': {
      id: '/createTournament'
      path: '/createTournament'
      fullPath: '/createTournament'
      preLoaderRoute: typeof CreateTournamentImport
      parentRoute: typeof rootRoute
    }
    '/loadTournament': {
      id: '/loadTournament'
      path: '/loadTournament'
      fullPath: '/loadTournament'
      preLoaderRoute: typeof LoadTournamentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CreateTournamentRoute,
  LoadTournamentRoute,
})

/* prettier-ignore-end */
